platform: x64

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"

install:
  - ps: python -m pip install --upgrade pip
  - ps: python -m pip install numpy pytest

build_script:
  - ps: python setup.py install

test_script:
    - ps: python -m pytest setup.py install
