platform: x64

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET PYTHONPATH=%PYTHON%\\Lib\\site-packages;%PYTHONPATH%"
  - ps: python -m pip install --upgrade pip setuptools
  - ps: python -m pip install numpy pytest

build_script:
  - ps: "ls"
  - ps: python setup.py install

test_script:
    - ps: python -m pytest
